
version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tracko
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    
  backend:
    build: ./backend
    image: backend-image:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend/index.js:/app/backend/index.js
      - ./backend/package.json:/app/backend/package.json
      - ./backend/prisma/schema.prisma:/app/backend/prisma/schema.prisma

  frontend:
    build: ./frontend
    image: frontend-image:latest
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
      - ./frontend/package.json:/app/frontend/package.json


