
version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tracko
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    image: backend-image:latest
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    image: frontend-image:latest
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend


