version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tracko
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - mynetwork 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    image: backend-image:latest
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./backend/index.js:/app/backend/index.js
      - ./backend/package.json:/app/backend/package.json
      - ./backend/prisma/schema.prisma:/app/backend/prisma/schema.prisma
    networks:
      - mynetwork
    command: sh -c "[ ! -f /app/backend/migration-done ] && npx prisma db push && touch /app/backend/migration-done; node /app/backend/index.js"

  frontend:
    build: ./frontend
    image: frontend-image:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/public:/app/frontend/public
      - ./frontend/package.json:/app/frontend/package.json
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
